sbatch run.sh LHX9  
sbatch run.sh ATF3  
sbatch run.sh PKNOX1  
sbatch run.sh NFIC  
sbatch run.sh T  
sbatch run.sh MAF  
sbatch run.sh ZNF580  
sbatch run.sh SNAI3  
sbatch run.sh HESX1  
sbatch run.sh JUN  
sbatch run.sh RFX3  
sbatch run.sh ZNF784  
sbatch run.sh GBX2  
sbatch run.sh EN2  
sbatch run.sh YY2  
sbatch run.sh SOX7  
sbatch run.sh MSC  
sbatch run.sh CREB5  
sbatch run.sh NFATC1  
sbatch run.sh CUX1  
sbatch run.sh NFKB2  
sbatch run.sh MYOG  
sbatch run.sh PAX8  
sbatch run.sh HOXC9  
sbatch run.sh ELK3  
sbatch run.sh NHLH2  
sbatch run.sh HLF  
sbatch run.sh HOXA10  
sbatch run.sh KLF13  
sbatch run.sh FIGLA  
sbatch run.sh ETV1  
sbatch run.sh NR2F1  
sbatch run.sh ETV7  
sbatch run.sh GLI3  
sbatch run.sh TFE3  
sbatch run.sh NFE2  
sbatch run.sh OLIG3  
sbatch run.sh NRL  
sbatch run.sh FOXB1  
sbatch run.sh TFAP2E  
sbatch run.sh RFX1  
sbatch run.sh VSX1  
sbatch run.sh HOXD13  
sbatch run.sh HSF4  
sbatch run.sh HSF2  
sbatch run.sh ETV5  
sbatch run.sh ESX1  
sbatch run.sh HOXC4  
sbatch run.sh ZNF140  
sbatch run.sh ETV4  
sbatch run.sh JUND  
sbatch run.sh EGR3  
sbatch run.sh MEIS3  
sbatch run.sh ELK1  
sbatch run.sh FOXR2  
sbatch run.sh PHOX2B  
sbatch run.sh JDP2  
sbatch run.sh UBP1  
sbatch run.sh FOXA1  
sbatch run.sh IRF8  
sbatch run.sh VENTX  
sbatch run.sh POU3F2  
sbatch run.sh ZNF524  
sbatch run.sh LHX6  
sbatch run.sh ZBTB26  
sbatch run.sh ELF1  
sbatch run.sh SCRT1  
sbatch run.sh GCM1  
sbatch run.sh LMX1B  
sbatch run.sh ZNF32  
sbatch run.sh KLF12  
sbatch run.sh OVOL1  
sbatch run.sh NEUROG1  
sbatch run.sh ELF5  
sbatch run.sh OLIG2  
sbatch run.sh FERD3L  
sbatch run.sh ZNF75A  
sbatch run.sh BHLHE23  
sbatch run.sh EGR1  
sbatch run.sh HOXC11  
sbatch run.sh HOXA6  
sbatch run.sh ZNF396  
sbatch run.sh MEIS2  
sbatch run.sh ELF3  
sbatch run.sh DLX4  
sbatch run.sh DLX5  
sbatch run.sh MEF2B  
sbatch run.sh ISX  
sbatch run.sh ALX1  
sbatch run.sh IRF3  
sbatch run.sh ZIC1  
sbatch run.sh EMX1  
sbatch run.sh CREB3L4  
sbatch run.sh YY1  
sbatch run.sh GATA3  
sbatch run.sh IRF9  
sbatch run.sh DUXA  
sbatch run.sh TBX3  
sbatch run.sh ATF2  
sbatch run.sh MIXL1  
sbatch run.sh OTX1  
sbatch run.sh ATF6B  
sbatch run.sh DMRTA1  
sbatch run.sh POU5F1  
sbatch run.sh TGIF2LX  
sbatch run.sh ZNF740  
sbatch run.sh HSF1  
sbatch run.sh MAFG  
sbatch run.sh NR5A1  
sbatch run.sh NFATC3  
sbatch run.sh CLOCK  
sbatch run.sh GATA5  
sbatch run.sh SNAI2  
sbatch run.sh ELF2  
sbatch run.sh LHX8  
sbatch run.sh PAX7  
sbatch run.sh TBX20  
sbatch run.sh NHLH1  
sbatch run.sh E2F4  
sbatch run.sh GRHL1  
sbatch run.sh FLI1  
sbatch run.sh TFCP2  
sbatch run.sh ALX3  
sbatch run.sh TFAP2A  
sbatch run.sh SNAI1  
sbatch run.sh HOXC10  
sbatch run.sh DBP  
sbatch run.sh FEV  
sbatch run.sh ATOH1  
sbatch run.sh SKOR2  
sbatch run.sh HOXB13  
sbatch run.sh CEBPB  
sbatch run.sh ERG  
sbatch run.sh SPIB  
sbatch run.sh ESRRG  
sbatch run.sh MYBL2  
sbatch run.sh CEBPE  
sbatch run.sh PROP1  
sbatch run.sh VSX2  
sbatch run.sh HOXA13  
sbatch run.sh MBNL2  
sbatch run.sh SPDEF  
sbatch run.sh ZNF597  
sbatch run.sh CREB1  
sbatch run.sh POU4F3  
sbatch run.sh CDX1  
sbatch run.sh GCM2  
sbatch run.sh VAX2  
sbatch run.sh HOXD10  
sbatch run.sh TFAP2B  
sbatch run.sh DLX1  
sbatch run.sh MYOD1  
sbatch run.sh FOXA2  
sbatch run.sh RAX  
sbatch run.sh BHLHA15  
sbatch run.sh YBX1  
sbatch run.sh RFX2  
sbatch run.sh ETV2  
sbatch run.sh NFIX  
sbatch run.sh IRF7 