sbatch run.sh ZNF281
sbatch run.sh NOTO
sbatch run.sh SOX12
sbatch run.sh BCL6B
sbatch run.sh IRF6
sbatch run.sh GSX2
sbatch run.sh ONECUT3
sbatch run.sh GMEB2
sbatch run.sh POU2F3
sbatch run.sh ZIC4
sbatch run.sh DPRX
sbatch run.sh KLF6
sbatch run.sh DMBX1
sbatch run.sh FOXN2
sbatch run.sh MTF1
sbatch run.sh FOXG1
sbatch run.sh IRX3
sbatch run.sh SOX14
sbatch run.sh ZNF444
sbatch run.sh ZIC3
sbatch run.sh HOXD11
sbatch run.sh RORB
sbatch run.sh DMRTC2
sbatch run.sh ZSCAN1
sbatch run.sh TBX21
sbatch run.sh ZSCAN9
sbatch run.sh HOXD1
sbatch run.sh NR5A2
sbatch run.sh SP2
sbatch run.sh ZBTB33
sbatch run.sh RHOXF1
sbatch run.sh BSX
sbatch run.sh ZBTB20
sbatch run.sh HMBOX1
sbatch run.sh TCF7L1
sbatch run.sh NFIB
sbatch run.sh NKX3-2
sbatch run.sh SOHLH2
sbatch run.sh NR1I3
sbatch run.sh GSX1
sbatch run.sh GLIS2
sbatch run.sh ARNT2
sbatch run.sh NFATC2
sbatch run.sh NFAT5
sbatch run.sh LIN28B
sbatch run.sh TGIF2LY
sbatch run.sh NKX2-5
sbatch run.sh HOXD8
sbatch run.sh SKOR1
sbatch run.sh OSR1
sbatch run.sh DPF1
sbatch run.sh ONECUT1
sbatch run.sh ZNF323
sbatch run.sh SP9
sbatch run.sh ZBTB14
sbatch run.sh MSX1
sbatch run.sh BATF
sbatch run.sh ZBTB45
sbatch run.sh TBX2
sbatch run.sh DLX2
sbatch run.sh GATA2
sbatch run.sh PITX3
sbatch run.sh EGR4
sbatch run.sh TEAD2
sbatch run.sh RARA
sbatch run.sh BARHL2
sbatch run.sh SIX4
sbatch run.sh ISL1
sbatch run.sh HMX2
sbatch run.sh HOXA9
sbatch run.sh FOXQ1
sbatch run.sh HOXB7
sbatch run.sh PAX2
sbatch run.sh KLF5
sbatch run.sh ZBED1
sbatch run.sh ZNF282
sbatch run.sh ASCL2
sbatch run.sh NR2F6
sbatch run.sh LEF1
sbatch run.sh ZBTB7A
sbatch run.sh SOX30
sbatch run.sh MEOX1
sbatch run.sh HOXB2
sbatch run.sh HMX1
sbatch run.sh ATF7
sbatch run.sh GMEB1
sbatch run.sh ZBTB32
sbatch run.sh FOXO4
sbatch run.sh RHOXF2
sbatch run.sh HEY1
sbatch run.sh PHOX2A
sbatch run.sh BARHL1
sbatch run.sh USF2
sbatch run.sh ZNF501
sbatch run.sh NEUROD1
sbatch run.sh IRX5
sbatch run.sh HOXA11
sbatch run.sh KLF3
sbatch run.sh NR4A1
sbatch run.sh HOXB4
sbatch run.sh FOXO3
sbatch run.sh ELK4
sbatch run.sh FOXI1
sbatch run.sh MAFF
sbatch run.sh CUX2
sbatch run.sh TBX18
sbatch run.sh ESRRB
sbatch run.sh PROX1
sbatch run.sh POU3F1
sbatch run.sh HOXA2
sbatch run.sh TLX2
sbatch run.sh CPSF4
sbatch run.sh PITX1
sbatch run.sh BATF3
sbatch run.sh SP3
sbatch run.sh HSFY1
sbatch run.sh DMRT3
sbatch run.sh E2F2
sbatch run.sh IRF2
sbatch run.sh BHLHE41
sbatch run.sh PBX1
sbatch run.sh ZNF713
sbatch run.sh HEY2
sbatch run.sh MAFA
sbatch run.sh ZFP41
sbatch run.sh ZNF660
sbatch run.sh MSGN1
sbatch run.sh SIX6
sbatch run.sh TFAP2C
sbatch run.sh ETS2
sbatch run.sh SREBF2
sbatch run.sh ZNF174
sbatch run.sh FOXK1
sbatch run.sh POU2F2
sbatch run.sh TCF21
sbatch run.sh EGR2
sbatch run.sh CDX4
sbatch run.sh ZBTB22
sbatch run.sh TCF4
sbatch run.sh EN1
sbatch run.sh GATA1
sbatch run.sh KLF4
sbatch run.sh ZSCAN16
sbatch run.sh ZNF454
sbatch run.sh TGIF2
sbatch run.sh BARX2
sbatch run.sh RFX7
sbatch run.sh HAND2
sbatch run.sh RUNX3
sbatch run.sh EVX1
sbatch run.sh POU4F1
sbatch run.sh MNX1
sbatch run.sh GLI2
sbatch run.sh GFI1
sbatch run.sh NR1D1
sbatch run.sh ISL2
sbatch run.sh RUNX2
sbatch run.sh ZNF821
sbatch run.sh ETV3
sbatch run.sh HOXB5
sbatch run.sh MLX
sbatch run.sh ALX4
sbatch run.sh CREB3L1
sbatch run.sh NR1I2
sbatch run.sh KLF14
sbatch run.sh ZNF410
sbatch run.sh POU1F1
sbatch run.sh TEF
sbatch run.sh DRGX
sbatch run.sh NR6A1
sbatch run.sh TFEC
sbatch run.sh XPA
sbatch run.sh KLF11
sbatch run.sh TFAP4
sbatch run.sh DMRTA2
sbatch run.sh BACH2
sbatch run.sh OSR2
sbatch run.sh CREM
sbatch run.sh HOXD9
sbatch run.sh ZNF276
sbatch run.sh PRRX2
sbatch run.sh FOXJ2
sbatch run.sh HES5
sbatch run.sh MAX
sbatch run.sh TCF12
sbatch run.sh LHX4
sbatch run.sh HSF5
sbatch run.sh DMRT1
sbatch run.sh ESR1
sbatch run.sh HOXC8
sbatch run.sh RARB
sbatch run.sh MEF2C
sbatch run.sh TBX19
sbatch run.sh SOX9
sbatch run.sh EOMES
sbatch run.sh HES7
sbatch run.sh SIX2
sbatch run.sh TFEB
sbatch run.sh NKX2-8
sbatch run.sh ZBTB37
sbatch run.sh TLX3
sbatch run.sh BCL11B
sbatch run.sh ELF4
sbatch run.sh LMX1A
sbatch run.sh MSX2
sbatch run.sh ZNF343
sbatch run.sh CEBPD
sbatch run.sh HOXC12
sbatch run.sh RORC
sbatch run.sh MEF2D
sbatch run.sh HOXB8
sbatch run.sh FOXL2
sbatch run.sh ZFP42
sbatch run.sh PAX9
sbatch run.sh RFX5
sbatch run.sh POU6F1
sbatch run.sh ASCL1
sbatch run.sh RXRB
sbatch run.sh NR2E1
sbatch run.sh ZNF771
sbatch run.sh POU3F4
sbatch run.sh BHLHE22
sbatch run.sh DLX6
sbatch run.sh SOX8
sbatch run.sh ATOH7
sbatch run.sh EVX2
sbatch run.sh LHX5
sbatch run.sh E2F3
sbatch run.sh HOXD3
sbatch run.sh FOS
sbatch run.sh NKX6-2
sbatch run.sh FOXD3
sbatch run.sh JUNB
sbatch run.sh KLF10
sbatch run.sh PRDM4
sbatch run.sh SP1
sbatch run.sh HOXC13
sbatch run.sh NKX6-3
sbatch run.sh KLF2
sbatch run.sh ZNF23
sbatch run.sh CREB3
sbatch run.sh IRF4
sbatch run.sh SREBF1
sbatch run.sh SIX1
sbatch run.sh ZNF385D
sbatch run.sh NFATC4
sbatch run.sh DLX3
sbatch run.sh ZNF250
sbatch run.sh SOX18
sbatch run.sh HIC1
sbatch run.sh PRDM1
sbatch run.sh ATF4
sbatch run.sh ARX
sbatch run.sh TBX1
sbatch run.sh GATA6
sbatch run.sh PAX3
sbatch run.sh SOX3
sbatch run.sh HOXD12
sbatch run.sh NKX3-1
sbatch run.sh FOXD2
sbatch run.sh NR1D2
sbatch run.sh PAX4
sbatch run.sh FOXJ3
sbatch run.sh HOXB9
sbatch run.sh SP8
sbatch run.sh PTF1A
sbatch run.sh ZBTB12
sbatch run.sh ARGFX
sbatch run.sh ZNF684
sbatch run.sh ONECUT2
sbatch run.sh SOX10
sbatch run.sh CRX
sbatch run.sh NR3C1
sbatch run.sh ARNTL
sbatch run.sh SHOX
sbatch run.sh CEBPG
sbatch run.sh NR3C2
sbatch run.sh FOXP1
sbatch run.sh KLF16
sbatch run.sh MESP2
sbatch run.sh ZNF76
sbatch run.sh TBX15
sbatch run.sh GSC
sbatch run.sh HES6
sbatch run.sh ZBTB18
sbatch run.sh SMAD5
sbatch run.sh ZSCAN5
sbatch run.sh ATF6
sbatch run.sh GATA4
sbatch run.sh HES1
sbatch run.sh SIX3
sbatch run.sh PKNOX2
sbatch run.sh HOXD4
sbatch run.sh KLF15
sbatch run.sh FOSB
sbatch run.sh PITX2
sbatch run.sh BCL6
sbatch run.sh ZBTB2
sbatch run.sh ZNF704
sbatch run.sh NEUROD2
sbatch run.sh ZNF296
sbatch run.sh E2F8
sbatch run.sh OVOL2
sbatch run.sh NR4A2
sbatch run.sh ZNF384
sbatch run.sh TEAD1
sbatch run.sh ZIC5
sbatch run.sh TFCP2L1
sbatch run.sh RXRA
sbatch run.sh TBX6
sbatch run.sh ESRRA
sbatch run.sh MYF6
sbatch run.sh BHLHE40
sbatch run.sh E2F7
sbatch run.sh GSC2
sbatch run.sh PDX1
sbatch run.sh VAX1
sbatch run.sh NKX2-3
sbatch run.sh HOXA7
sbatch run.sh ZNF449
sbatch run.sh BBX
sbatch run.sh SOX4
sbatch run.sh ZNF263
sbatch run.sh HOXA4
sbatch run.sh TGIF1
sbatch run.sh RXRG
sbatch run.sh ZNF274
sbatch run.sh LBX2
sbatch run.sh ZBTB7B
sbatch run.sh FOSL1
sbatch run.sh PAX6
sbatch run.sh ZNF345
sbatch run.sh GLIS1
sbatch run.sh E2F1
sbatch run.sh SRF
sbatch run.sh THRB
sbatch run.sh ZNF177
sbatch run.sh HOXA1
sbatch run.sh IRF5
sbatch run.sh ZFP1
sbatch run.sh GABPA
sbatch run.sh OTX2
sbatch run.sh FOXP3
sbatch run.sh GFI1B
sbatch run.sh ZNF12
sbatch run.sh PPARD
sbatch run.sh MEOX2
sbatch run.sh RFX4
sbatch run.sh RARG
sbatch run.sh HOXA5
sbatch run.sh NR2C1
sbatch run.sh PAX1
sbatch run.sh TCF7
sbatch run.sh NEUROG2
sbatch run.sh EMX2
sbatch run.sh SCRT2
sbatch run.sh USF1
sbatch run.sh ZSCAN23
sbatch run.sh CDX2
sbatch run.sh HSFY2
sbatch run.sh XBP1
sbatch run.sh HES2
sbatch run.sh ZSCAN4
sbatch run.sh HOXB1
sbatch run.sh FOXA3
sbatch run.sh ZNF787
sbatch run.sh NPAS2
sbatch run.sh ZBTB43
sbatch run.sh FOXC2
sbatch run.sh LHX1
sbatch run.sh IRX1
sbatch run.sh HNF4A
sbatch run.sh FOXE1